monitoring/apps/core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('index/', views.index, name='main'),
]

monitoring/apps/cpu/urls.py
from django.urls import path

from . import views


app_name = 'cpu'

urlpatterns = [
    path('dashboard/', views.CpuLoadView.as_view(), name='dashboard'),
    path('moments/', views.BaseListResource.as_view(), name='list'),
    path('average/', views.AverageListResource.as_view(), name='average_list'),
]

monitoring/config/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('apps.core.urls', namespace='core'),),
    path('cpu/', include('apps.cpu.urls', namespace='cpu'),),
    path('', lambda request: redirect('core:main')),
]

monitoring/apps/cpu/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _

from .managers import CpuLoadManager

# Create your models here.


class CpuLoad(models.Model):
    """Мониторинг загрузки процессора"""
    created_at = models.DateTimeField(
        _('Creation date and time'), auto_now_add=True,
    )
    value = models.FloatField(
        _('CPU usage in percent'),
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
    )

    objects = CpuLoadManager()

monitoring/apps/core/views.py
from django.shortcuts import render


def index(request):
    """Главная страница"""
    return render(request, 'base.html')

monitoring/apps/cpu/views.py
from operator import itemgetter

from django.http import JsonResponse
from django.utils import timezone
from django.views.generic import ListView
from django.views import View

from .models import CpuLoad


class CpuLoadView(ListView):
    """Страница мониторинга"""
    model = CpuLoad
    queryset = CpuLoad.objects.with_last_hour_loads()
    template_name = 'cpu/dashboard.html'
    # ordering = ('created_at',)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['loads'] = round(len(context['object_list'])/720*100, 2)
        context['idle'] = round(100 - context['loads'], 2)
        # Коррекция, если был период простоя
        now = timezone.now()
        context['starts_at'] = now - timezone.timedelta(hours=1)
        context['ends_at'] = now
        print('loads:', len(context['object_list']))
        return context


class BaseListResource(View):
    def get(self, request):
        qs = list(
            CpuLoad.objects.with_last_hour_loads().order_by('created_at').values()
        )
        ends_at = timezone.now()
        starts_at = ends_at - timezone.timedelta(hours=1)

        time_labels = update_null(qs, starts_at)
        return JsonResponse({
            'loads': time_labels,
            'ends_at': ends_at, 'starts_at': starts_at
        })


class AverageListResource(View):
    def get(self, request):
        qs = list(
            CpuLoad.objects.with_last_hour_loads().order_by('created_at').values()
        )
        ends_at = timezone.now()
        starts_at = ends_at - timezone.timedelta(hours=1)
        time_labels = update_null(qs, starts_at)
        average_labels = []
        ends = starts_at + timezone.timedelta(minutes=1)
        avg_min = []
        for time_label in time_labels:
            if time_label['created_at'] <= ends:
                avg_min.append(time_label)
            else:
                avg = sum(tl['value'] for tl in avg_min)/len(avg_min)
                average_labels.append({
                    'created_at': ends - timezone.timedelta(seconds=30),
                    'value': avg
                })
                avg_min = [time_label]
                ends = ends + timezone.timedelta(minutes=1)

        return JsonResponse({
            'loads': average_labels,
            'ends_at': ends_at, 'starts_at': starts_at
        })


def update_null(time_labels, start):
    extra_labels = []
    for time_label in time_labels:
        if (time_label['created_at'] - start) > timezone.timedelta(seconds=5):
            extra_labels.append({
                'created_at': start + timezone.timedelta(seconds=5),
                'value': 0
            })
            start = start + timezone.timedelta(seconds=5)
        else:
            start = time_label['created_at']
    time_labels.extend(extra_labels)
    time_labels.sort(key=itemgetter('created_at'))
    return time_labels

monitoring/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% trans "CPU Monitoring" %}{% endblock %}</title>

  {% include 'includes/bootstrap_css.html' %}
  <link rel="stylesheet" href="{% static 'site/css/base.css' %}">
</head>
<body>
  <div class="loading"></div>

  <!-- Навигационная панель -->
  {% include 'navbar.html' %}
  {# Нужно загружать скрипты в начале из-за datepicker #}
  {% include 'includes/bootstrap_scripts.html' %}

  <!-- ---------------------------- Нижняя часть ----------------------------- -->
  <!-- Основной раздел -->

  <div class="container-fluid">
    <div class="row">

      {% include 'leftmenu.html' %}

      <div id="main" class="col-sm-9">
        <!-- Дополнительный div для выравнивания flex-элементов .card при растягивании левого меню #side-menu -->
        <div id="main-block">

          <!-- <div class="row w-100"> -->
          {% block content %}
          {% comment %}
            {% if cards|length > 1 %}
              {% for card in cards %}
                {% include 'cards/many_cards.html' %}
              {% endfor %}
            {% else %}
              {% include 'cards/one_card.html' %}
            {% endif %}
          {% endcomment %}
            {% endblock content %}
          <!-- </div> -->

        </div> <!-- end of .main-block -->
      </div> <!-- end of #main -->
    </div> <!-- end of .row основного раздела-->
  </div> <!-- end of .container-fluid основного раздела -->

<!-- ------------------------------- Скрипты ------------------------------- -->


<script src="{% static 'site/js/monitoring.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

monitoring/templates/cpu/dashboard.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Dashboard" %}{% endblock title %}

{% block content %}
<div class="card" id="pie-charts">
    <div class="card-block">
        <h2>Общий анализ</h2>
        <div class="round-chart" data-percent="{{ loads }}">
            <span>
                {{ loads }}
                <small>
                    % <br>
                    работал
                </small>
            </span>
        </div>
    </div>
</div>

<div class="card" id="quick-info">
    <div class="card-block">
        <h2>Краткая статистика</h2>
        <div class="quick-stats">
            <strong>Начало периода:</strong>
            <span>{{ starts_at }}</span>
        </div>
        <div class="quick-stats">
            <strong>Конец периода:</strong>
            <span>{{ ends_at }}</span>
        </div>
        <div class="quick-stats">
            <strong>CPU работал:</strong>
            <span>{{ loads }} %</span>
        </div>
        <div class="quick-stats">
            <strong>CPU простаивал:</strong>
            <span>{{ idle }} %</span>
        </div>
    </div>
</div>

<div id="ration-stock" class="card col-sm-12">
    <div class="card-block">
        <h2>5-секундные отметки времени</h2>
        <canvas id="chart1"></canvas>
    </div>
    <div class="card-block">
        <h2>Усредненные 1-минутные значения</h2>
        <canvas id="chart2"></canvas>
    </div>
</div>
{% endblock %}

monitoring/templates/includes/bootstrap_css.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

monitoring/templates/includes/bootstrap_scripts.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
    integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
    integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/easy-pie-chart/2.1.6/jquery.easypiechart.min.js"
    integrity="sha512-DHNepbIus9t4e6YoMBSJLwl+nnm0tIwMBonsQQ+W9NKN6gVVVbomJs9Ii3mQ+HzGZiU5FyJLdnAz9a63ZgZvTQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js"></script>

monitoring/templates/leftmenu.html
{% load i18n %}
{% load static %}
<div id="side-menu" class="col-sm-3 d-none d-sm-block">
    <div class="leftside-block">
      <div class="profile-block">
        <img src="{% static 'site/images/no-user-image.gif' %}" alt="no image" class="rounded-circle">
        <h4 class="profile-title">{% trans "Anonymous User" %}</h4>
      </div>

      <ul class="nav nav-pills flex-column">

        <li class="nav-item">
          <a href="{% url 'cpu:dashboard' %}" class="nav-link transition">
            <span class="fa fa-home fa-fw" aria-hidden="true"></span>
            {% trans "Overview" %}
          </a>
        </li>

      </ul>

    </div>
  </div>

monitoring/templates/navbar.html
{% load i18n %}
{% load static %}
<nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
    <div class="col-sm-3 top-left-menu d-flex">

        <a href="#" class="navbar-brand"><h1>{% trans "Monitoring Dashboard" %}</h1></a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-menu"
                aria-controls="nav-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

    </div>

    <div id="nav-menu" class="collapse navbar-collapse justify-content-end">

      <!-- Круглая кнопка профиля -->
      <div id="nav-profile" class="btn-group">
        <button type="button" class="btn btn-link dropdown-toggle caret-off"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'site/images/no-user-image.gif' %}" alt="{% trans 'no image' %}" class="img-thumbnail rounded-circle">
        </button>

        <ul class="dropdown-menu dropdown-menu-right">
          {% if user.is_authenticated %}
          <li>
            <a href="#" class="transition">{% trans "Profile" %}</a>
          </li>
          <li>
            <a href="#" class="transition">{% trans "Settings" %}</a>
          </li>
          {% else %}
          <li>
            <a href="#" class="transition">{% trans "Sign in" %}</a>
          </li>
          {% endif %}
          <li class="dropdown-divider"></li>
          {% if user.is_authenticated %}
          <li>
            <a href="#" class="transition">{% trans "Logout" %}</a>
          </li>
          {% else %}
          <li>
            <a href="#" class="transition">{% trans "Sign up" %}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>